.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH temper-nagios-plugin 1 "November 11, 2010" "" "TEMPer Nagios Plugin"

.SH NAME
temper-nagios-plugin \- program for...

.SH SYNOPSIS
.B temper-nagios-plugin
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the
.B temper-nagios-plugin
program. This program...
.PP
\fBtemper-nagios-plugin\fP is for...

.SH OPTIONS
.B
.IP -OPTION
This option...

.SH "EXIT STATUS"

.SH NOTES

.SH BUGS

.SH EXAMPLE

.SH "SEE ALSO"


